# -*- coding: utf-8 -*-

import os
import sys

def change_dynamic_require(dynamic_require_line):
	page_file_path = './node_modules/reactman/lib/component/page/Page.react.js'

	items = []
	src_file = open(page_file_path)
	for line in src_file:
		line = line.rstrip()
		if '//for windows cnpm' in line:
			if not line.startswith('//'):
				items.append('//' + line)
			else:
				items.append(line)
		elif '//for mac cnpm' in line:
			if not line.startswith('//'):
				items.append('//' + line)
			else:
				items.append(line)
			items.append(dynamic_require_line + ' //dynamic require generated by dist')
		elif '//dynamic require generated by dist' in line:
			pass
		else:
			items.append(line)
	content = '\n'.join(items)
	src_file.close()

	dst_file = open(page_file_path, 'w')
	print >> dst_file, content
	dst_file.close()

if __name__ == '__main__':
	if os.name == 'nt' or os.name == 'posix':
		print '[fix_webpack_dynamic_require]: os is %s, use 8 depths path' % os.name
		dynamic_require_line = "var dynamicRequire = require('../../../../../../../../static/component/dynamic_require');"
	else:
		print '[fix_webpack_dynamic_require]: os is %s, use 5 depths path' % os.name
		dynamic_require_line = "var dynamicRequire = require('../../../../../static/component/dynamic_require');"
	change_dynamic_require(dynamic_require_line)
